# For full config options, check the docs:
#    docs.serverless.com
service: serverless-template 

plugins:
  - serverless-appsync-plugin
  - serverless-plugin-typescript
  - serverless-pseudo-parameters
  # - serverless-dynamodb-local
  - serverless-offline
  # - aws-amplify-serverless-plugin

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-1'}
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
    DB_NAME: 'test'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'

custom:
  stage: ${opt:stage, 'dev'}
  output:
    file: .serverless/output.json
  dynamodb:
    stage:
      - dev
      - offline
    start:
      port: 8000
    #   inMemory: true
    #   migrate: true
    # migration:
    #   dir: offline/migrations
  appSync:
    name: userinfo_backend
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: ap-northeast-1
      userPoolId
      defaultAction: ALLOW
    schema: schema.graphql
    dataSources:
      - type: AMAZON_DYNAMODB
        name: test
        description: user管理テーブル
        config:
          tableName: test
          serviceRoleArn:
          region: ap-northeast-1
    mappingTemplatesLocation: mapping-templates
    mappingTemplates:
      - dataSource: test
        type: Query
        field: listTest_appsuncs
        # kind: PIPELINE
        # request: 'start.vtl'
        # response: 'end.vtl'
        # functions:
        #   - GetUser
    # functionConfigurations:
    #   - dataSource: dynamo_user
    #     name: 'GetUser'
    #     request: 'GetUser.req.vtl'
    #     response: 'GetUser.res.vtl'

package:
  exclude:
    - node_modules/**
  include:
    - serverless.yml
    - .serverless/**

resources:
  Outputs:
    ApiUrl:
      Description: "The API Gateway URL"
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}"
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    GatewayResponseDefault5XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
  # Resources:
  #   TodosDynamoDbTable:
  #     Type: 'AWS::DynamoDB::Table'
  #     DeletionPolicy: Retain
  #     Properties:
  #       AttributeDefinitions:
  #         -
  #           AttributeName: name
  #           AttributeType: S
  #       KeySchema:
  #         -
  #           AttributeName: name
  #           KeyType: HASH
  #       ProvisionedThroughput:
  #         ReadCapacityUnits: 1
  #         WriteCapacityUnits: 1
  #       TableName: ${self:provider.environment.DYNAMODB_TABLE}

functions:
  pgCheck:
    handler: src/functions/pgCheck.list
    role:
    description: posrgre crud
    events:
      - http:
          path: pg
          method: get
          # cors: 
          #   origin:
          #     # - '*'
          #     # - "https://master.d2w7htrom5yxv0.amplifyapp.com"
          #     # - "https://dev.d10apifivscxf5.amplifyapp.com"
          #     - "http://localhost:3000"
          #   headers: 
          #     - Content-Type
          #     - Origin
          #     - Authorization
          #     - Accept
          #     - X-Requested-With
          #   allowCredentials: true
  #         layers:
  #           - "arn:aws:lambda:ap-northeast-1:388865528159:layer:pg-sequelize:4"
  healthcheck:
    handler: src/functions/healthcheck.healthcheck
    description: aws:states:opt-out
    events:
      - http:
          path: healthcheck
          method: get
          # cors: 
          #   method: 
          #     - get
            # origin:
            #   # - '*'
            #   # - "https://master.d2w7htrom5yxv0.amplifyapp.com"
            #   # - "https://dev.d10apifivscxf5.amplifyapp.com"
            #   - "http://localhost:3000"
            # headers: 
            #   - Content-Type
            #   - Origin
            #   - Authorization
            #   - X-Api-Key
            #   - Accept
            #   - X-Requested-With
            # allowCredentials: true
