# For full config options, check the docs:
#    docs.serverless.com
service: serverless-template 

plugins:
  - serverless-plugin-typescript
  - serverless-pseudo-parameters
  # - serverless-dynamodb-local
  - serverless-offline
  # - aws-amplify-serverless-plugin

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-1'}
  role: arn:aws:iam::388865528159:role/serverless-template-dev-ap-northeast-1-lambdaRole
  vpc:
    securityGroupIds:
      - sg-0c66673331d7e786a
    subnetIds:
      - subnet-063bc89ddcd0d099f
      - subnet-08a3b69654a268e63
      - subnet-0c34570ad93f2ebb7
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
    DB_PORT: 5432
    DB_HOST: 'bopista-platform-lambda-rds-proxy.proxy-ceqbm7arub9o.ap-northeast-1.rds.amazonaws.com'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'

custom:
  stage: ${opt:stage, 'dev'}
  output:
    file: .serverless/output.json
  # dynamodb:
  #   stage:
  #     - dev
  #     - offline
  #   start:
  #     port: 8000
  #     inMemory: true
  #     migrate: true
  #   migration:
  #     dir: offline/migrations

package:
  exclude:
    - node_modules/**
  include:
    - serverless.yml
    - .serverless/**

resources:
  Outputs:
    ApiUrl:
      Description: "The API Gateway URL"
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}"
  # Resources:
  #   TodosDynamoDbTable:
  #     Type: 'AWS::DynamoDB::Table'
  #     DeletionPolicy: Retain
  #     Properties:
  #       AttributeDefinitions:
  #         -
  #           AttributeName: name
  #           AttributeType: S
  #       KeySchema:
  #         -
  #           AttributeName: name
  #           KeyType: HASH
  #       ProvisionedThroughput:
  #         ReadCapacityUnits: 1
  #         WriteCapacityUnits: 1
  #       TableName: ${self:provider.environment.DYNAMODB_TABLE}

functions:
  pgCheck:
    handler: src/functions/pgCheck.list
    role: arn:aws:iam::388865528159:role/serverless-template-dev-ap-northeast-1-lambdaRole
    description: posrgre crud
    events:
      - http:
          path: pg
          method: get
          cors: 
            origin:
              - "https://master.d2w7htrom5yxv0.amplifyapp.com"
              - "http://localhost:3000"
            headers: 
              - "Content-Type"
              - "Origin"
              - "Authorization"
              - "Accept"
              - "X-Requested-With"
            allowCredentials: true
          layers:
            - "arn:aws:lambda:ap-northeast-1:388865528159:layer:pg-sequelize:4"
  healthcheck:
    handler: src/functions/healthcheck.healthcheck
    description: aws:states:opt-out
    events:
      - http:
          path: healthcheck
          method: get
          cors: 
            origin:
              - "https://master.d2w7htrom5yxv0.amplifyapp.com"
              - "http://localhost:3000"
            headers: 
              - "Content-Type"
              - "Origin"
              - "Authorization"
              - "X-Api-Key"
              - "Accept"
              - "X-Requested-With"
            allowCredentials: true
