# For full config options, check the docs:
#    docs.serverless.com
service: serverless-template 

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-stack-output
  - aws-amplify-serverless-plugin

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:stage, 'ap-northeast-1'}

custom:
  stage: ${opt:stage, 'dev'}
  output:
    file: .serverless/output.json
  amplify:
    # this can be anything, as long as the frontend project includes it
    - filename: src/aws-exports.js
      type: javascript

package:
  exclude:
    - node_modules/**
  include:
    - serverless.yml

resources:
  Outputs:
    ApiUrl:
      Description: "The API Gateway URL"
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}"

functions:
  healthcheck:
    handler: src/functions/healthcheck.healthcheck
    description: aws:states:opt-out
    events:
      - http:
          path: healthcheck
          method: get